### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by entrepaman** [balloob/react-sidebar#166]
After installing the react-sidebar using npm and running the project I'm getting the following error

    Failed to compile.

    ./node_modules/react-sidebar/dist/react-sidebar.esm.js
    Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized' in 'D:\reactProjects\evaluiz\code\node_modules\react-sidebar\dist'

Project Code

    import React, { Component } from 'react';
    import Sidebar from 'react-sidebar';

    import Aux from '../Auxiliary/Auxiliary';

    import classes from './Layout.css';

    class Layout extends Component {
        state = {
            sidebarOpen: true
        }

        onSideBarOpen = (open) => {
            this.setState(prevState => ({
                sidebarOpen: open
            }));
        }

        render() {
            return (
                <Aux>
                    <Sidebar 
                        sidebar={<b>Sidebar Content</b>}
                        open={thinpms.state.sidebarOpen}
                        onSetOpen={this.onSideBarOpen}
                    >
                        <button onClick={() => this.onSetSidebarOpen(true)}>Open sidebar</button>
                    </Sidebar>
                    <main className={classes.Content}>
                        {this.props.children}
                    </main>
                </Aux>
            );
        }
    }

    export default Layout;

**Comment by markusenglund** [comment]
Wow, big mistake by me. Fixing ASAP.

**Comment by entrepaman** [comment]
Thanks in advance

**Comment by markusenglund** [comment]
Ok, I just released 3.0.2 which should fix the problem. Please update to this version.

The problem stemmed from the `@babel/runtime` package which had a breaking change from version `7.0.0-beta.55` -> `7.0.0-beta.56`. React sidebar imported the babel helpers from (among others) `@babel/runtime/helpers/builtin/assertThisInitialized` which was moved to `@babel/runtime/helpers/assertThisInitialized`. I fixed the problem by updating the babel dependencies of react-sidebar to `7.0.0-beta.56`.

My mistake was to have React-sidebar depend on the babel 7 beta which is not stable. However, since babel 7 stable release is right around the corner now, I will not bother changing back to babel 6 since it would be too much work.

**Comment by entrepaman** [comment]
Thanks a lot @markusenglund for quiz response. I'm closing this
