### ISSUE TITLE
Update Example Code in Readme

### ISSUE THREAD

**Issue by palamccc** [balloob/react-sidebar#33]
I installed react-sidebar today and got version 2.1.1 from npm. I think latest version uses new es7 module syntax.

But Readme in github uses commonjs syntax.

**Comment by balloob** [comment]
The ES2015 class is the source code but the `package.json` points at the ES5 version. No need to update it.

**Comment by palamccc** [comment]
Few hours ago, I installed it, and require('react-sidebar') is not working. to make it work, i am actually using it as 

```
var Sidebar = require('react-sidebar').default;
```
Instead of 
```
var Sidebar = require('react-sidebar');
```

I am not good in new module syntax, But in below file, there is no module.exports , so just require('react-sidebar') wont work.
https://github.com/balloob/react-sidebar/blob/master/dist-modules/index.js

**Comment by Cleod9** [comment]
@balloob Curious, why did you close this issue? Seems like it might be a good idea to at least update the readme. Since ES6 modules are still fairly new, it might be a good idea to instruct folks using ES5 that they will need to write `require('react-sidebar').default || require('react-sidebar');`. Your current solution will only import properly as-is if the consumer us using an ES6 transpiler that can interpret the `__esModule` flag (such as babel)

Related discussion: https://github.com/esnext/es6-module-transpiler/issues/85

**Comment by balloob** [comment]
My bad. Both of you are right. Updated the README: 4241bbda5897e9dd8357ac92eb3d8c33e39916c6
